title = "Yash Sharma"
name = "Yash Sharma"
description = "Personal site"
url = "https://thestaccato.github.io"
baseurl = ""
locale = "en-US"

[social]
email = "none@example.org"
#googlescholar = "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
#orcid = "https://orcid.org"
github = "thestaccato"
#gitlab = "gitlab.com"
#git = "https://git.org"
codeberg = "thestaccato"
#forgejo = "https://git.kernal.org"
matrix = "https://matrix.org"
#linkedin = "yourlinkedin"
#bluesky = "bsky.app"
#mastodon = "https://mastodon.social/@yourusername"
#sourcehut = "https://sr.ht"
#fediverse = "https://your-fediverse-instance/@you"
#kofi = "https://ko-fi.com/yourusername"
